import assert from "node:assert/strict";
import { readFileSync } from "node:fs";

const shell = readFileSync("src/components/project-shell.tsx", "utf8");
const editor = readFileSync("src/components/workspace/editor-pane.tsx", "utf8");
const compileRoute = readFileSync("src/app/api/latex/compile/route.ts", "utf8");
const projectTypes = readFileSync("src/types/project.ts", "utf8");
const packageJson = JSON.parse(readFileSync("package.json", "utf8"));

assert.match(shell, /useState<ProjectFile\[\]>\(sampleFiles\)/, "Project files must become stateful for insertion");
assert.match(shell, /const generatedFigurePath = "figures\/generated\/diagram_001\.tex"/, "Approved diagram source must target figures/generated");
assert.match(shell, /sourcePath: generatedFigurePath/, "Preview source path must point to the generated figure file");
assert.match(shell, /onKeepDiagram=\{keepDiagram\}/, "Keep Diagram must run the insertion workflow");
assert.match(shell, /insertApprovedDiagram\(projectFiles, diagramPreview\)/, "Insertion must use current project files and approved preview");
assert.match(shell, /saveGeneratedFigureSource\(files, preview\.sourcePath, preview\.source\)/, "Insertion must save approved TikZ source");
assert.match(shell, /sanitizeGeneratedTikzSource\(source\)\.trim\(\)/, "Saved generated figures must sanitize model TikZ before insertion");
assert.match(shell, /sanitizeGeneratedFigureFiles\(files\)/, "Compile must sanitize already-staged generated figure files");
assert.match(shell, /createPostCompileAutoFix\(compilableFiles, initialResult\)/, "Compile must run a deterministic post-render auto-fix pass");
assert.match(shell, /repairGeneratedLatexColorAliases/, "Post-render auto-fix must repair generated xcolor aliases");
assert.match(shell, /amber: "orange"/, "Post-render auto-fix must map web color aliases to xcolor colors");
assert.match(shell, /compileRepairedProjectFiles/, "Post-render auto-fix must recompile after patching generated source");
assert.match(shell, /insertDiagramInputIntoMain\(file\.content, preview\)/, "Insertion must patch main.tex");
assert.match(projectTypes, /insertionOffset: number \| null/, "Preview approval must retain the requested cursor insertion offset");
assert.match(shell, /latestMainCursorRef/, "Inline insertion must preserve the last main.tex cursor");
assert.match(shell, /getDiagramInsertionOffset\(request, activeFile, latestCursorRef\.current, latestMainCursorRef\.current, projectFiles\)/, "Inline insertion must capture the editor cursor");
assert.match(shell, /preview\.outputTarget === "inline"/, "Insertion must branch on inline cursor target");
assert.match(shell, /insertInlineDiagramAtOffset\(mainSource, preview\)/, "Inline insertion must insert at the captured cursor offset");
assert.match(shell, /\\input\{\$\{inputPath\}\}/, "Inserted figure block must input the generated source");
assert.match(shell, /createResponsiveFigureInput/, "Inserted diagrams must use a responsive input wrapper");
assert.match(shell, /ensureDiagramLatexDependencies/, "Insertion must add parent-document diagram dependencies");
assert.match(shell, /ensureUsePackage\(withGraphicx, "tikz"\)/, "Insertion must add TikZ when generated source uses tikzpicture");
assert.match(shell, /ensureTikzLibraries\(withTikz/, "Insertion must add common TikZ libraries");
assert.match(shell, /\\label\{fig:generated-diagram-001\}/, "Inserted figure block must include a stable label");
assert.match(shell, /diagramInsertionMarker/, "Insertion must target the existing editor placeholder");
assert.match(shell, /naturalLanguageDiagramRequestMarker/, "Insertion must recognize natural-language placeholder comments in real papers");
assert.match(shell, /replaceNaturalLanguageDiagramPlaceholder/, "Insertion must replace the existing placeholder figure body");
assert.match(shell, /setActiveFileId\("main"\)/, "After insertion the main document should become active");
assert.match(shell, /setLastDiagramInsertionUndo/, "Diagram insertion must store an undo snapshot");
assert.match(shell, /undoDiagramInsertion/, "Diagram insertion must be reversible");
assert.match(shell, /setCompileState\("running"\)[\s\S]*setCompileState\("success"\)/, "Insertion must trigger main document compile status");
assert.match(shell, /diagram inserted into \$\{insertion\.mainFilePath\}; compiling main document/, "Status must confirm insertion and main-document compile");
assert.match(shell, /fetch\("\/api\/latex\/compile"/, "Compile must render the current project through the LaTeX compile route");
assert.match(compileRoute, /compileWithDocker\(workspacePath, mainPath\)/, "Compile route must render through Docker");
assert.match(compileRoute, /texlive\/texlive:latest/, "Compile route must use the multi-architecture TeX Live Docker image");
assert.match(compileRoute, /getDockerPlatformArgs/, "Compile route must allow an explicit Docker platform override");
assert.doesNotMatch(compileRoute, /PDFLATEX_BIN|compileWithLocalPdflatex/, "Compile route must not fall back to local pdflatex");
assert.match(compileRoute, /createLatexErrorSummary/, "Compile route must summarize the first actionable LaTeX error");
assert.match(editor, /value=\{file\.content\}/, "Editor must receive current file content as controlled state");
assert.match(editor, /onChangeFileContent\(file\.id, value \?\? ""\)/, "Editor edits must update project file state");
assert.match(editor, /onDidChangeCursorPosition/, "Editor must report cursor moves for inline insertion");
assert.match(editor, /getTargetAtClientPoint/, "Right-click insertion must move the cursor to the clicked location");
assert.match(packageJson.scripts.test, /task-017-document-insertion/, "TASK-017 checks must run in npm test");

console.log("TASK-017 document insertion checks passed");
