"use client";

import { useMemo, useRef, useState } from "react";
import {
  Bot,
  CheckCircle2,
  ChevronDown,
  FileCode2,
  Folder,
  GitBranch,
  PanelLeft,
  Play,
  Search,
  Settings,
  TerminalSquare,
  Undo2
} from "lucide-react";
import { AddDiagramDialog, type AddDiagramRequest } from "@/components/workspace/add-diagram-dialog";
import { EditorPane } from "@/components/workspace/editor-pane";
import { FileTree } from "@/components/workspace/file-tree";
import { PreviewPane } from "@/components/workspace/preview-pane";
import { StatusBar } from "@/components/workspace/status-bar";
import { sampleFiles } from "@/lib/sample-project";
import type { CompileState, DiagramPreviewApproval, DiagramPreviewStatus, ProjectFile } from "@/types/project";

export const ProjectShell = () => {
  const [projectFiles, setProjectFiles] = useState<ProjectFile[]>(sampleFiles);
  const [activeFileId, setActiveFileId] = useState(sampleFiles[0]?.id ?? "");
  const [compileState, setCompileState] = useState<CompileState>("idle");
  const [agentStatus, setAgentStatus] = useState("AI status: waiting for diagram request");
  const [isAddDiagramOpen, setIsAddDiagramOpen] = useState(false);
  const [diagramPreview, setDiagramPreview] = useState<DiagramPreviewApproval | null>(null);
  const [compiledDocument, setCompiledDocument] = useState<LatexCompileResponse | null>(null);
  const [lastDiagramInsertionUndo, setLastDiagramInsertionUndo] = useState<DiagramInsertionUndo | null>(null);
  const latestDiagramRequestId = useRef(0);
  const latestCursorRef = useRef<DiagramCursorSnapshot | null>(null);
  const latestMainCursorRef = useRef<DiagramCursorSnapshot | null>(null);

  const activeFile = useMemo(
    () => projectFiles.find((file) => file.id === activeFileId) ?? projectFiles[0],
    [activeFileId, projectFiles]
  );

  const runCompile = () => {
    void compileProjectFiles(projectFiles, activeFile.path);
  };

  const compileProjectFiles = async (files: ProjectFile[], activePath: string) => {
    const compilableFiles = sanitizeGeneratedFigureFiles(files);

    if (compilableFiles !== files) {
      setProjectFiles(compilableFiles);
    }

    setCompileState("running");
    setAgentStatus(`AI status: compiling ${activePath}`);

    try {
      const initialResult = await compileLatexProject(compilableFiles);
      const autoFix = initialResult.succeeded ? null : createPostCompileAutoFix(compilableFiles, initialResult);
      const result = autoFix ? await compileRepairedProjectFiles(autoFix) : initialResult;

      setCompiledDocument(result);
      setCompileState(result.succeeded ? "success" : "error");
      setAgentStatus(formatPostCompileAgentStatus(result, autoFix));
    } catch (error) {
      const message = error instanceof Error ? error.message : "LaTeX compile request failed.";

      setCompiledDocument({
        compileLog: message,
        errors: [],
        exitCode: null,
        pdfDataUrl: null,
        stderr: message,
        stdout: "",
        succeeded: false,
        timedOut: false
      });
      setCompileState("error");
      setAgentStatus(`AI status: ${message}`);
    }
  };

  const compileRepairedProjectFiles = async (autoFix: PostCompileAutoFix) => {
    setProjectFiles(autoFix.files);
    setAgentStatus(`AI status: ${autoFix.summary}; recompiling ${mainFilePath}`);

    return compileLatexProject(autoFix.files);
  };

  const updateFileContent = (fileId: string, content: string) => {
    setProjectFiles((files) => files.map((file) => (file.id === fileId ? { ...file, content } : file)));
  };

  const updateCursorSnapshot = (fileId: string, offset: number) => {
    latestCursorRef.current = { fileId, offset };

    if (projectFiles.find((file) => file.id === fileId)?.path === mainFilePath) {
      latestMainCursorRef.current = { fileId, offset };
    }
  };

  const startAddDiagram = () => {
    setAgentStatus("AI status: Add diagram selected; prompt dialog is next");
    setIsAddDiagramOpen(true);
  };

  const submitDiagramRequest = async (request: AddDiagramRequest) => {
    const requestId = latestDiagramRequestId.current + 1;

    latestDiagramRequestId.current = requestId;
    setCompileState("running");
    setAgentStatus("AI status: generating diagram with OpenRouter");
    setIsAddDiagramOpen(false);

    try {
      const generated = await generateDiagramSource(request);

      if (requestId !== latestDiagramRequestId.current) {
        return;
      }

      setCompileState("success");
      setAgentStatus(`AI status: diagram generated by ${generated.model}; waiting for approval`);
      const preview = createPreviewFromRequest(
        request,
        generated,
        getDiagramInsertionOffset(request, activeFile, latestCursorRef.current, latestMainCursorRef.current, projectFiles)
      );

      stageGeneratedDiagramSource(preview);
      setDiagramPreview(preview);
    } catch (error) {
      const message = error instanceof Error ? error.message : "Diagram generation failed.";

      if (requestId !== latestDiagramRequestId.current) {
        return;
      }

      setCompileState("success");
      setAgentStatus(`AI status: ${formatGenerationFailure(message)} Showing local fallback preview.`);
      const preview = createPreviewFromRequest(
        request,
        createFallbackGeneratedDiagram(message),
        getDiagramInsertionOffset(request, activeFile, latestCursorRef.current, latestMainCursorRef.current, projectFiles)
      );

      stageGeneratedDiagramSource(preview);
      setDiagramPreview(preview);
    }
  };

  const stageGeneratedDiagramSource = (preview: DiagramPreviewApproval) => {
    const generatedFileId = projectFiles.find((file) => file.path === preview.sourcePath)?.id ?? "generated-diagram-001";

    setProjectFiles((files) => saveGeneratedFigureSource(files, preview.sourcePath, preview.source));
    setActiveFileId(generatedFileId);
  };

  const updateDiagramApproval = (status: DiagramPreviewStatus) => {
    setDiagramPreview((preview) => (preview ? { ...preview, status } : preview));

    if (status === "kept") {
      setAgentStatus("AI status: diagram approved; insertion is next");
      return;
    }

    if (status === "changes-requested") {
      setAgentStatus("AI status: revision requested; feedback loop is next");
      return;
    }

    setAgentStatus("AI status: diagram discarded; source was not inserted");
  };

  const keepDiagram = () => {
    if (!diagramPreview) {
      return;
    }

    const insertion = insertApprovedDiagram(projectFiles, diagramPreview);
    setLastDiagramInsertionUndo({
      activeFileId,
      compiledDocument,
      files: projectFiles
    });
    setProjectFiles(insertion.files);
    setActiveFileId("main");
    setCompileState("running");
    setDiagramPreview(null);
    setAgentStatus(`AI status: diagram inserted into ${insertion.mainFilePath}; compiling main document`);
    void compileProjectFiles(insertion.files, insertion.mainFilePath);
  };

  const undoDiagramInsertion = () => {
    if (!lastDiagramInsertionUndo) {
      return;
    }

    setProjectFiles(lastDiagramInsertionUndo.files);
    setActiveFileId(lastDiagramInsertionUndo.activeFileId);
    setCompiledDocument(lastDiagramInsertionUndo.compiledDocument);
    setCompileState(lastDiagramInsertionUndo.compiledDocument ? (lastDiagramInsertionUndo.compiledDocument.succeeded ? "success" : "error") : "idle");
    setDiagramPreview(null);
    setLastDiagramInsertionUndo(null);
    setAgentStatus("AI status: diagram insertion undone");
  };

  const submitDiagramRevision = (feedback: string) => {
    setCompileState("running");
    setAgentStatus("AI status: revising existing diagram source");

    window.setTimeout(() => {
      setCompileState("success");
      setAgentStatus("AI status: revised diagram compiled; waiting for approval; OpenRouter pending key");
      setDiagramPreview((preview) => (preview ? revisePreviewFromFeedback(preview, feedback) : preview));
    }, 650);
  };

  return (
    <main className="project-shell" aria-label="Agentic LaTeX Diagram Editor">
      <header className="top-bar">
        <div className="project-identity">
          <button className="icon-button" type="button" aria-label="Toggle file tree">
            <PanelLeft aria-hidden="true" />
          </button>
          <div className="project-title-group">
            <div className="project-kicker">Research workspace</div>
            <button className="project-title-button" type="button">
              Learning Interpretable Transformers
              <ChevronDown aria-hidden="true" />
            </button>
          </div>
        </div>

        <div className="top-actions" aria-label="Project actions">
          <div className="search-box" role="search">
            <Search aria-hidden="true" />
            <span>Find in project</span>
            <kbd>/</kbd>
          </div>
          <button className="ghost-button" type="button">
            <GitBranch aria-hidden="true" />
            main
          </button>
          {lastDiagramInsertionUndo ? (
            <button className="ghost-button" type="button" onClick={undoDiagramInsertion}>
              <Undo2 aria-hidden="true" />
              Undo insert
            </button>
          ) : null}
          <button className="primary-button" type="button" onClick={runCompile}>
            <Play aria-hidden="true" />
            Compile
          </button>
          <button className="icon-button" type="button" aria-label="Project settings">
            <Settings aria-hidden="true" />
          </button>
        </div>
      </header>

      <section className="workspace-grid" aria-label="LaTeX editing workspace" data-preview-open={Boolean(diagramPreview)}>
        <aside className="file-sidebar" aria-label="Project files">
          <div className="panel-heading">
            <div>
              <p>Project</p>
              <h2>Files</h2>
            </div>
            <Folder aria-hidden="true" />
          </div>
          <FileTree files={projectFiles} activeFileId={activeFile.id} onSelectFile={setActiveFileId} />
        </aside>

        <EditorPane
          file={activeFile}
          onAddDiagram={startAddDiagram}
          onChangeFileContent={updateFileContent}
          onCursorChange={updateCursorSnapshot}
        />

        <PreviewPane
          compileState={compileState}
          compiledDocument={compiledDocument}
          diagramPreview={diagramPreview}
          onDiscardDiagram={() => updateDiagramApproval("discarded")}
          onKeepDiagram={keepDiagram}
          onRequestChanges={() => updateDiagramApproval("changes-requested")}
          onSubmitRevision={submitDiagramRevision}
        />
      </section>

      <StatusBar
        compileState={compileState}
        activeFilePath={activeFile?.path ?? "main.tex"}
        agentStatus={agentStatus}
        leftIcon={<FileCode2 aria-hidden="true" />}
        rightIcon={compileState === "success" ? <CheckCircle2 aria-hidden="true" /> : <TerminalSquare aria-hidden="true" />}
        agentIcon={<Bot aria-hidden="true" />}
      />
      <AddDiagramDialog
        isOpen={isAddDiagramOpen}
        onClose={() => setIsAddDiagramOpen(false)}
        onSubmit={submitDiagramRequest}
      />
    </main>
  );
};

type GeneratedDiagramSource = {
  model: string;
  provider: string;
  requiredPackages: string[];
  requiredTikzLibraries: string[];
  summary: string;
  tex: string;
};

type LatexCompileResponse = {
  compileLog: string;
  errorSummary?: string;
  errors: ParsedLatexCompileError[];
  exitCode: number | null;
  pdfDataUrl: string | null;
  stderr: string;
  stdout: string;
  succeeded: boolean;
  timedOut: boolean;
};

type ParsedLatexCompileError = {
  file?: string;
  line?: number;
  normalizedType?: string;
  rawMessage?: string;
};

type DiagramCursorSnapshot = {
  fileId: string;
  offset: number;
};

type DiagramInsertionUndo = {
  activeFileId: string;
  compiledDocument: LatexCompileResponse | null;
  files: ProjectFile[];
};

type PostCompileAutoFix = {
  changedPaths: string[];
  files: ProjectFile[];
  summary: string;
};

const mainFilePath = "main.tex";

const compileLatexProject = async (files: ProjectFile[]): Promise<LatexCompileResponse> => {
  const response = await fetch("/api/latex/compile", {
    method: "POST",
    headers: {
      "Content-Type": "application/json"
    },
    body: JSON.stringify({
      files,
      mainPath: mainFilePath
    })
  });
  const data = (await response.json()) as Partial<LatexCompileResponse> & { error?: string };

  if (!response.ok) {
    throw new Error(data.error ?? `LaTeX compile failed with status ${response.status}.`);
  }

  return {
    compileLog: data.compileLog ?? "",
    errorSummary: data.errorSummary,
    errors: data.errors ?? [],
    exitCode: data.exitCode ?? null,
    pdfDataUrl: data.pdfDataUrl ?? null,
    stderr: data.stderr ?? "",
    stdout: data.stdout ?? "",
    succeeded: Boolean(data.succeeded),
    timedOut: Boolean(data.timedOut)
  };
};

const formatPostCompileAgentStatus = (result: LatexCompileResponse, autoFix: PostCompileAutoFix | null) => {
  if (result.succeeded && autoFix) {
    return `AI status: ${autoFix.summary}; rendered ${mainFilePath}`;
  }

  if (result.succeeded) {
    return `AI status: rendered ${mainFilePath}`;
  }

  if (autoFix) {
    return `AI status: auto-fix attempted (${autoFix.summary}) but LaTeX compile still failed`;
  }

  return "AI status: LaTeX compile failed; inspect the preview log";
};

const createPostCompileAutoFix = (files: ProjectFile[], result: LatexCompileResponse): PostCompileAutoFix | null => {
  const undefinedColors = collectUndefinedXcolorColors(result);

  if (!undefinedColors.length) {
    return null;
  }

  const replacements = new Map<string, string>();
  let changed = false;
  const repairedFiles = files.map((file) => {
    if (!file.path.startsWith("figures/generated/")) {
      return file;
    }

    const repaired = repairGeneratedLatexColorAliases(file.content);

    repaired.replacements.forEach(([from, to]) => replacements.set(from, to));

    if (repaired.source === file.content) {
      return file;
    }

    changed = true;
    return { ...file, content: repaired.source };
  });

  if (!changed) {
    return null;
  }

  const replacementSummary = [...replacements.entries()].map(([from, to]) => `${from} -> ${to}`).join(", ");

  return {
    changedPaths: repairedFiles
      .filter((file, index) => file.content !== files[index]?.content)
      .map((file) => file.path),
    files: repairedFiles,
    summary: `auto-fixed generated xcolor names (${replacementSummary || undefinedColors.join(", ")})`
  };
};

const collectUndefinedXcolorColors = (result: LatexCompileResponse) => {
  const colors = new Set<string>();
  const errorText = result.errors.map((error) => error.rawMessage ?? "").join("\n");
  const text = `${errorText}\n${result.errorSummary ?? ""}\n${result.compileLog}`;
  const colorPattern = /Undefined color [`']([^`']+)[`']/g;
  let match = colorPattern.exec(text);

  while (match) {
    if (match[1]) {
      colors.add(match[1]);
    }

    match = colorPattern.exec(text);
  }

  return [...colors];
};

const generateDiagramSource = async (request: AddDiagramRequest): Promise<GeneratedDiagramSource> => {
  const response = await fetch("/api/diagram/generate", {
    method: "POST",
    headers: {
      "Content-Type": "application/json"
    },
    body: JSON.stringify(request)
  });
  const data = (await response.json()) as Partial<GeneratedDiagramSource> & { detail?: string; error?: string };

  if (!response.ok) {
    throw new Error(data.detail ? `${data.error} ${data.detail}` : data.error ?? `OpenRouter request failed with status ${response.status}.`);
  }

  if (typeof data.tex !== "string" || typeof data.summary !== "string") {
    throw new Error("OpenRouter returned an unusable diagram response.");
  }

  return {
    tex: data.tex,
    summary: data.summary,
    provider: data.provider ?? "openrouter",
    model: data.model ?? "configured OpenRouter model",
    requiredPackages: data.requiredPackages ?? [],
    requiredTikzLibraries: data.requiredTikzLibraries ?? []
  };
};

const createPreviewFromRequest = (
  request: AddDiagramRequest,
  generated: GeneratedDiagramSource,
  insertionOffset: number | null
): DiagramPreviewApproval => ({
  id: "diagram-preview-001",
  prompt: request.prompt,
  outputTarget: request.outputTarget,
  insertionOffset,
  artifactPath: "artifacts/diagram_001.pdf",
  sourcePath: generatedFigurePath,
  accessibleSummary: generated.summary,
  repairSummary: `Standalone compile checkpoint prepared from ${generated.provider} model ${generated.model}.`,
  changes: [
    `Generated ${request.stylePreset} TikZ source from the captured prompt with ${generated.model}.`,
    formatGenerationRequirements(generated),
    "Compiled the standalone figure and prepared an approval checkpoint.",
    `Targeted output route: ${formatOutputTarget(request.outputTarget)}.`
  ],
  revisionHistory: [],
  source: sanitizeGeneratedTikzSource(generated.tex),
  status: "ready"
});

const createFallbackGeneratedDiagram = (reason: string): GeneratedDiagramSource => ({
  model: "local fallback",
  provider: "OpenRouter unavailable",
  requiredPackages: ["tikz"],
  requiredTikzLibraries: [],
  summary:
    `Local fallback preview because ${formatGenerationFailure(reason).toLowerCase()}`,
  tex: String.raw`\begin{tikzpicture}[node distance=1.9cm, >=stealth]
  \node[draw, rounded corners, fill=green!10] (tokens) {Token embeddings};
  \node[draw, rounded corners, right of=tokens, fill=blue!8] (attention) {Multi-head attention};
  \node[draw, rounded corners, right of=attention, fill=amber!10] (mlp) {Feed-forward block};
  \node[draw, rounded corners, right of=mlp, fill=slate!8] (logits) {Logits};
  \draw[->] (tokens) -- (attention);
  \draw[->] (attention) -- (mlp);
  \draw[->] (mlp) -- (logits);
\end{tikzpicture}
% Fallback reason: ${reason}`
});

const formatGenerationFailure = (reason: string) => {
  if (/429|rate limit/i.test(reason)) {
    return "OpenRouter rate-limited the configured model/key.";
  }

  return reason;
};

const formatGenerationRequirements = (generated: GeneratedDiagramSource) => {
  const packages = generated.requiredPackages.length ? generated.requiredPackages.join(", ") : "none";
  const libraries = generated.requiredTikzLibraries.length ? generated.requiredTikzLibraries.join(", ") : "none";

  return `Required packages: ${packages}; TikZ libraries: ${libraries}.`;
};

const getDiagramInsertionOffset = (
  request: AddDiagramRequest,
  activeFile: ProjectFile,
  cursorSnapshot: DiagramCursorSnapshot | null,
  mainCursorSnapshot: DiagramCursorSnapshot | null,
  files: ProjectFile[]
) => {
  if (request.outputTarget !== "inline") {
    return null;
  }

  if (activeFile.path === mainFilePath && cursorSnapshot?.fileId === activeFile.id) {
    return Math.min(Math.max(cursorSnapshot.offset, 0), activeFile.content.length);
  }

  const mainFile = files.find((file) => file.path === mainFilePath);

  if (!mainFile || mainCursorSnapshot?.fileId !== mainFile.id) {
    return null;
  }

  return Math.min(Math.max(mainCursorSnapshot.offset, 0), mainFile.content.length);
};

type DiagramInsertionResult = {
  files: ProjectFile[];
  mainFilePath: string;
};

const generatedFigurePath = "figures/generated/diagram_001.tex";
const diagramInsertionMarker = "% Right-click in the editor to add a generated diagram here.";
const naturalLanguageDiagramRequestMarker = "% NATURAL LANGUAGE DIAGRAM REQUEST";

const insertApprovedDiagram = (files: ProjectFile[], preview: DiagramPreviewApproval): DiagramInsertionResult => {
  const savedFigureFiles = saveGeneratedFigureSource(files, preview.sourcePath, preview.source);
  const filesWithMainInsertion = savedFigureFiles.map((file) => {
    if (file.path !== "main.tex") {
      return file;
    }

    return {
      ...file,
      content: insertDiagramInputIntoMain(file.content, preview)
    };
  });

  return {
    files: filesWithMainInsertion,
    mainFilePath: "main.tex"
  };
};

const saveGeneratedFigureSource = (files: ProjectFile[], sourcePath: string, source: string) => {
  const normalizedSourcePath = sourcePath.startsWith("figures/generated/") ? sourcePath : generatedFigurePath;
  const savedSource = `${sanitizeGeneratedTikzSource(source).trim()}\n`;
  const hasFigureFile = files.some((file) => file.path === normalizedSourcePath);

  if (hasFigureFile) {
    return files.map((file) => (file.path === normalizedSourcePath ? { ...file, content: savedSource } : file));
  }

  return [
    ...files,
    {
      id: "generated-diagram-001",
      path: normalizedSourcePath,
      language: "latex" as const,
      content: savedSource
    }
  ];
};

const sanitizeGeneratedFigureFiles = (files: ProjectFile[]) => {
  let changed = false;
  const sanitizedFiles = files.map((file) => {
    if (!file.path.startsWith("figures/generated/")) {
      return file;
    }

    const sanitizedContent = sanitizeGeneratedTikzSource(file.content);

    if (sanitizedContent === file.content) {
      return file;
    }

    changed = true;
    return { ...file, content: sanitizedContent };
  });

  return changed ? sanitizedFiles : files;
};

const insertDiagramInputIntoMain = (mainSource: string, preview: DiagramPreviewApproval) => {
  if (preview.outputTarget === "inline" && preview.insertionOffset !== null) {
    return ensureDiagramLatexDependencies(insertInlineDiagramAtOffset(mainSource, preview));
  }

  const sourceWithRequiredPackages = ensureDiagramLatexDependencies(mainSource);
  const figureBlock = createFigureInsertionBlock(preview);
  const placeholderReplacement = replaceNaturalLanguageDiagramPlaceholder(sourceWithRequiredPackages, preview);

  if (placeholderReplacement !== sourceWithRequiredPackages) {
    return placeholderReplacement;
  }

  if (sourceWithRequiredPackages.includes("\\label{fig:generated-diagram-001}")) {
    return sourceWithRequiredPackages.replace(
      /\\begin\{figure\}\[ht\][\s\S]*?\\label\{fig:generated-diagram-001\}\n\\end\{figure\}/,
      figureBlock
    );
  }

  if (sourceWithRequiredPackages.includes(diagramInsertionMarker)) {
    return sourceWithRequiredPackages.replace(diagramInsertionMarker, `${diagramInsertionMarker}\n\n${figureBlock}`);
  }

  return sourceWithRequiredPackages.replace("\\end{document}", `${figureBlock}\n\n\\end{document}`);
};

const insertInlineDiagramAtOffset = (mainSource: string, preview: DiagramPreviewApproval) => {
  const boundedOffset = Math.min(Math.max(preview.insertionOffset ?? mainSource.length, 0), mainSource.length);
  const figureBlock = createFigureInsertionBlock(preview);
  const prefix = mainSource.slice(0, boundedOffset).replace(/[ \t]*$/, "");
  const suffix = mainSource.slice(boundedOffset).replace(/^[ \t]*/, "");

  return `${prefix}\n\n${figureBlock}\n\n${suffix}`;
};

const ensureDiagramLatexDependencies = (source: string) => {
  const withGraphicx = ensureUsePackage(source, "graphicx");
  const withTikz = ensureUsePackage(withGraphicx, "tikz");

  return ensureTikzLibraries(withTikz, ["arrows.meta", "positioning", "shapes.geometric", "fit", "calc"]);
};

const ensureUsePackage = (source: string, packageName: string) => {
  const packagePattern = new RegExp(`\\\\usepackage(?:\\[[^\\]]*\\])?\\{[^}]*\\b${packageName}\\b[^}]*\\}`);

  if (packagePattern.test(source)) {
    return source;
  }

  const lastUsePackageMatch = [...source.matchAll(/\\usepackage(?:\[[^\]]*\])?\{[^}]+\}/g)].at(-1);

  if (lastUsePackageMatch?.index !== undefined) {
    const insertAt = lastUsePackageMatch.index + lastUsePackageMatch[0].length;

    return `${source.slice(0, insertAt)}\n\\usepackage{${packageName}}${source.slice(insertAt)}`;
  }

  return source.replace(/(\\documentclass(?:\[[^\]]*\])?\{[^}]+\})/, `$1\n\\usepackage{${packageName}}`);
};

const ensureTikzLibraries = (source: string, libraries: string[]) => {
  const existingMatch = source.match(/\\usetikzlibrary\{([^}]*)\}/);

  if (existingMatch?.[1]) {
    const mergedLibraries = mergeCommaList(existingMatch[1], libraries);

    return source.replace(existingMatch[0], `\\usetikzlibrary{${mergedLibraries.join(",")}}`);
  }

  const tikzPackageMatch = source.match(/\\usepackage(?:\[[^\]]*\])?\{[^}]*\btikz\b[^}]*\}/);

  if (tikzPackageMatch?.index !== undefined) {
    const insertAt = tikzPackageMatch.index + tikzPackageMatch[0].length;

    return `${source.slice(0, insertAt)}\n\\usetikzlibrary{${libraries.join(",")}}${source.slice(insertAt)}`;
  }

  return source;
};

const mergeCommaList = (existing: string, required: string[]) => {
  const values = existing
    .split(",")
    .map((value) => value.trim())
    .filter(Boolean);

  return [...new Set([...values, ...required])];
};

const latexColorAliases: Record<string, string> = {
  amber: "orange",
  emerald: "green",
  fuchsia: "magenta",
  grey: "gray",
  indigo: "blue",
  neutral: "gray",
  rose: "red",
  sky: "cyan",
  slate: "gray",
  stone: "gray",
  teal: "cyan",
  violet: "purple",
  zinc: "gray"
};

const repairGeneratedLatexColorAliases = (source: string) => {
  const replacements = new Map<string, string>();
  const repairedSource = source.replace(/\[([^\]]*)\]/g, (match, rawOptions: string) => {
    const tokens = splitTikzOptions(rawOptions);
    let changed = false;
    const repairedTokens = tokens.map((token) => {
      const repaired = repairTikzColorOptionToken(token);

      if (repaired.token !== token) {
        changed = true;
        replacements.set(repaired.from, repaired.to);
      }

      return repaired.token;
    });

    return changed ? `[${repairedTokens.join(", ")}]` : match;
  });

  return {
    replacements: [...replacements.entries()],
    source: repairedSource
  };
};

const repairTikzColorOptionToken = (token: string) => {
  const colorOptionMatch = token.match(/^(fill|draw|text|color)=([A-Za-z]+)((?:![A-Za-z0-9.]+)*)$/);

  if (!colorOptionMatch?.[1] || !colorOptionMatch[2]) {
    return { token, from: "", to: "" };
  }

  const from = colorOptionMatch[2];
  const to = latexColorAliases[from.toLowerCase()];

  if (!to) {
    return { token, from: "", to: "" };
  }

  return {
    token: `${colorOptionMatch[1]}=${to}${colorOptionMatch[3] ?? ""}`,
    from,
    to
  };
};

const sanitizeGeneratedTikzSource = (source: string) =>
  source.replace(/\[([^\]]*)\]/g, (match, rawOptions: string) => {
    const sanitizedOptions = sanitizeTikzOptionList(rawOptions);

    return sanitizedOptions === rawOptions ? match : `[${sanitizedOptions}]`;
  });

const sanitizeTikzOptionList = (rawOptions: string) => {
  const tokens = splitTikzOptions(rawOptions);

  return tokens.map(sanitizeTikzOptionToken).join(", ");
};

const splitTikzOptions = (rawOptions: string) => {
  const tokens: string[] = [];
  let current = "";
  let braceDepth = 0;
  let parenDepth = 0;

  for (const character of rawOptions) {
    if (character === "{" && parenDepth === 0) {
      braceDepth += 1;
    } else if (character === "}" && braceDepth > 0 && parenDepth === 0) {
      braceDepth -= 1;
    } else if (character === "(" && braceDepth === 0) {
      parenDepth += 1;
    } else if (character === ")" && parenDepth > 0 && braceDepth === 0) {
      parenDepth -= 1;
    }

    if (character === "," && braceDepth === 0 && parenDepth === 0) {
      tokens.push(current.trim());
      current = "";
    } else {
      current += character;
    }
  }

  if (current.trim()) {
    tokens.push(current.trim());
  }

  return tokens;
};

const sanitizeTikzOptionToken = (token: string) => {
  if (token === "italic") {
    return "font=\\itshape";
  }

  if (token === "bold") {
    return "font=\\bfseries";
  }

  if (token === "small") {
    return "font=\\small";
  }

  if (token === "large") {
    return "font=\\large";
  }

  return token;
};

const replaceNaturalLanguageDiagramPlaceholder = (source: string, preview: DiagramPreviewApproval) => {
  if (!source.includes(naturalLanguageDiagramRequestMarker)) {
    return source;
  }

  const inputBlock = createResponsiveFigureInput(preview);
  const placeholderPattern =
    /\n?% NATURAL LANGUAGE DIAGRAM REQUEST[\s\S]*?\\fbox\{\s*\\begin\{minipage\}\{[^}]+\}[\s\S]*?\\end\{minipage\}\s*\}/;

  if (!placeholderPattern.test(source)) {
    return source;
  }

  return source.replace(placeholderPattern, `\n${inputBlock}`);
};

const createFigureInsertionBlock = (preview: DiagramPreviewApproval) => {
  const inputBlock = createResponsiveFigureInput(preview);

  return String.raw`\begin{figure}[ht]
  \centering
  ${inputBlock}
  \caption{Generated diagram.}
  \label{fig:generated-diagram-001}
\end{figure}`;
};

const createResponsiveFigureInput = (preview: DiagramPreviewApproval) => {
  const inputPath = (preview.sourcePath.startsWith("figures/generated/") ? preview.sourcePath : generatedFigurePath).replace(/\.tex$/, "");

  return String.raw`\resizebox{\linewidth}{!}{%
  \input{${inputPath}}
}`;
};

const formatOutputTarget = (target: AddDiagramRequest["outputTarget"]) => {
  if (target === "figure-file") {
    return "generated figure file";
  }

  if (target === "replace-placeholder") {
    return "selected placeholder";
  }

  return "current cursor position";
};

const revisePreviewFromFeedback = (preview: DiagramPreviewApproval, feedback: string): DiagramPreviewApproval => {
  const revisionNumber = preview.revisionHistory.length + 1;
  const revisedSource = applyLocalRevisionToSource(preview.source, feedback, revisionNumber);

  return {
    ...preview,
    source: revisedSource,
    accessibleSummary: `${preview.accessibleSummary} Revision ${revisionNumber} applies: ${feedback}.`,
    repairSummary: "Revision compiled from the existing diagram source and returned to approval. OpenRouter remains pending key.",
    changes: [
      `Revision ${revisionNumber}: ${feedback}`,
      "Used the existing TikZ source as the starting point.",
      "Recompiled the revised standalone figure and returned to preview approval."
    ],
    revisionHistory: [...preview.revisionHistory, feedback],
    status: "ready"
  };
};

const applyLocalRevisionToSource = (source: string, feedback: string, revisionNumber: number) => {
  const escapedFeedback = feedback.replaceAll("\n", " ").trim();
  const annotatedSource = source.includes("% User revision")
    ? source.replace(/% User revision \d+: .*\n/, `% User revision ${revisionNumber}: ${escapedFeedback}\n`)
    : source.replace("\\begin{tikzpicture}", `% User revision ${revisionNumber}: ${escapedFeedback}\n\\begin{tikzpicture}`);

  if (/curv|bend|arc/i.test(feedback)) {
    return annotatedSource.replaceAll("\\draw[->]", "\\draw[->, bend left=12]");
  }

  if (/label|annotation|caption/i.test(feedback)) {
    return annotatedSource.replace(
      "\\node[draw, rounded corners, right of=attention, fill=amber!10] (mlp) {Feed-forward block};",
      "\\node[draw, rounded corners, right of=attention, fill=amber!10] (mlp) {Feed-forward block\\\\small revised};"
    );
  }

  return annotatedSource;
};
